// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dive_into_grpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class GrpcDiver
{
  static readonly string __ServiceName = "GrpcDiver";

  static readonly grpc::Marshaller<global::DiveRequest> __Marshaller_DiveRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DiveRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::DiveResponse> __Marshaller_DiveResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DiveResponse.Parser.ParseFrom);

  static readonly grpc::Method<global::DiveRequest, global::DiveResponse> __Method_Dive = new grpc::Method<global::DiveRequest, global::DiveResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "Dive",
      __Marshaller_DiveRequest,
      __Marshaller_DiveResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::DiveIntoGrpcReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of GrpcDiver</summary>
  public abstract partial class GrpcDiverBase
  {
    public virtual global::System.Threading.Tasks.Task<global::DiveResponse> Dive(global::DiveRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for GrpcDiver</summary>
  public partial class GrpcDiverClient : grpc::ClientBase<GrpcDiverClient>
  {
    /// <summary>Creates a new client for GrpcDiver</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public GrpcDiverClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for GrpcDiver that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public GrpcDiverClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected GrpcDiverClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected GrpcDiverClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::DiveResponse Dive(global::DiveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Dive(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::DiveResponse Dive(global::DiveRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_Dive, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::DiveResponse> DiveAsync(global::DiveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return DiveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::DiveResponse> DiveAsync(global::DiveRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_Dive, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override GrpcDiverClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new GrpcDiverClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(GrpcDiverBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_Dive, serviceImpl.Dive).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, GrpcDiverBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_Dive, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DiveRequest, global::DiveResponse>(serviceImpl.Dive));
  }

}
#endregion
