// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: values.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class ValueService
{
  static readonly string __ServiceName = "ValueService";

  static readonly grpc::Marshaller<global::ValueRequest> __Marshaller_ValueRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ValueRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::ValueResponse> __Marshaller_ValueResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ValueResponse.Parser.ParseFrom);

  static readonly grpc::Method<global::ValueRequest, global::ValueResponse> __Method_GetValues = new grpc::Method<global::ValueRequest, global::ValueResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetValues",
      __Marshaller_ValueRequest,
      __Marshaller_ValueResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::ValuesReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of ValueService</summary>
  public abstract partial class ValueServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::ValueResponse> GetValues(global::ValueRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for ValueService</summary>
  public partial class ValueServiceClient : grpc::ClientBase<ValueServiceClient>
  {
    /// <summary>Creates a new client for ValueService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public ValueServiceClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for ValueService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public ValueServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected ValueServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected ValueServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::ValueResponse GetValues(global::ValueRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetValues(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::ValueResponse GetValues(global::ValueRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetValues, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::ValueResponse> GetValuesAsync(global::ValueRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetValuesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::ValueResponse> GetValuesAsync(global::ValueRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetValues, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override ValueServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new ValueServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(ValueServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_GetValues, serviceImpl.GetValues).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, ValueServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_GetValues, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ValueRequest, global::ValueResponse>(serviceImpl.GetValues));
  }

}
#endregion
